# Generated by Django 6.0.4 on 2026-04-20 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichier',
            options={'ordering': ['date_creation']},
        ),
        migrations.RenameField(
            model_name='fichier',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='dossier',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='dossier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='editor.dossier'),
            preserve_default=False,
        ),
    ]
